---
- hosts: all
  
  vars:
    users:
    -  "swathi"
    - "hegde"
    - "mohandas"
  tasks:
  - name: "Create user accounts"
    user:
      name: "{{ item }}"
      groups: "admin,www-data"
    with_items: "{{ users }}"
  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', '/home/'+ item + '/.ssh/id_rsa.pub') }}"
    with_items: "{{ users }}"
  - name: "Allow admin users to sudo without a password"
    lineinfile:
      dest: "/etc/sudoers" # path: in version 2.3
      state: "present"
      regexp: "^%admin"
      line: "%admin ALL=(ALL) NOPASSWD: ALL"
...
