---

- hosts: all
  
  tasks:
    - name: Reboot host
      shell: 'sleep 2 && shutdown -r now'
      async: 1
      poll: 0
      ignore_errors: yes
 
    - name: Waiting for server to come back 
      become: false
      local_action: wait_for host={{ inventory_hostname }} port=22
                    search_regex=OpenSSH state=started delay=5 
